basePath: /
definitions:
  response.APIResponse:
    properties:
      data: {}
      message:
        type: string
      success:
        type: boolean
    type: object
host: localhost:8080
info:
  contact:
    email: your-email@example.com
    name: Your Name
    url: https://your-website.com
  description: This is a simple CMS API with blog and menu features.
  title: CMS Project API
  version: "1.0"
paths:
  /api/nav_links:
    get:
      description: Retrieve a list of all navigation links (menus)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.APIResponse'
      summary: Get navigation links
      tags:
      - navigation
  /api/users:
    get:
      description: Retrieve a list of all users from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.APIResponse'
      summary: Get all users
      tags:
      - users
swagger: "2.0"
